/**:
  ros__parameters:
    # 相机唯一名称，用于枚举设备（需与 MVS 客户端中设置的设备用户定义名称一致）
    camera_name: "front_camera"

    # ROS2 坐标系 ID，推荐使用格式：[camera_name]_optical_frame
    frame_id: "front_camera_optical_frame"

    # 图像像素格式: 
    # "Keep": 保持 MVS 配置的原始格式（推荐，最省带宽）
    # 可选: "RGB8", "BGR8", "Mono8", "BayerRG8", "BayerBG8", "BayerGR8", "BayerGB8"
    pixel_format: "Keep"

    # 相机标定文件路径 (URI格式)

    camera_info_url: "package://hikvision_ros2_driver/config/camera_info.yaml"

    # 初始曝光时间 (单位: 微秒 us)
    # 范围由具体相机硬件决定，通常为 20.0 - 500000.0
    exposure_time: 10000.0

    # 初始增益 (单位: dB)
    # 范围由具体相机硬件决定，通常为 0.0 - 20.0
    gain: 8.0